version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:20.0.1
    environment:
      JASUR_TEST_VAR_1: "TEST VALUE 1"
      JASUR_TEST_VAR_2: "TEST VALUE 2"
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run: docker images
      - aws-ecr/build-and-push-image:
          create-repo: true
          dockerfile: Dockerfile
          extra-build-args: '--compress'
          push-image: true
          repo: 660990364978.dkr.ecr.ap-northeast-1.amazonaws.com/jasur-test-ecr
workflows:
  build-and-push:
    jobs:
      - build:
          context: aws-temp-context
