version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:20.0.1
    environment:
      JASUR_TEST_VAR_1: "TEST VALUE 1"
      JASUR_TEST_VAR_2: "TEST VALUE 2"
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run: docker images

workflows:
  build-and-push:
    jobs:
      - build


