version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.06
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run: docker images

workflows:
  build-and-push:
    jobs:
      - build
